name: test_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - zarr
  - xarray
  - h5netcdf
  - pandas
  - cfgrib
  - cftime
  - astropy
  - requests
  - aiohttp
  - pytest-cov
  - fsspec
  - dask
  - s3fs
  - python-blosc
  - flake8
  - black
  - pip
  - pip:
      - git+https://github.com/fsspec/filesystem_spec
