name: test_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - zarr
  - xarray
  - h5netcdf
  - pandas
  - cfgrib
  - pytest-cov
  - fsspec
  - dask
  - s3fs
  - flake8
  - black
