name: Tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [38, 39, 310]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          auto-activate-base: false
          activate-environment: test_env
          environment-file: ci/environment-py${{matrix.python-version}}.yml
      - name: Install kerchunk
        shell: bash -l {0}
        run: |
          pip install . -e
      - name: Test with pytest
        shell: bash -l {0}
        run: |
          pytest -v --cov
